### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by wikimatze** [bluz71/bluz71.github.io#1]
Is this it  possible to add this feature?

**Comment by bluz71** [comment]
Yes, it should be doable.

I'll look into it; I am new to this blogging business.

**Comment by bluz71** [comment]
I've set up the Jekyll Feed plugin which should auto-generate an Atom (RSS) feed.

[Here](https://bluz71.github.io/feed.xml) is the feed URL.

I'm not sure if I'm doing it right or not. Let me know, for now resolving.

**Comment by wikimatze** [comment]
According to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbluz71.github.io%2Ffeed.xml - everything is fine and I can now track your wonderful articles about Neovim. Thank you very much.
